export default {
    primary: "#FCAD70",
    secondary: "#BEC5F0",
    createAction: "#FCAD70",
    newMessage: "#FCAD70",
    hover: "#BEC6EF",
    iconMenus: "#0B062B",
    popup: "#DBE6F1",
    confirmButton: "#62A1F7",
    messageChat: "#4295F3",
    myMessageChat: "#99D28C",
    success: "#28a745",
    otherMessageChat: "#F1EAEA",
    backgroundConversationChat: "#BED9F3",
    benefits: "#BED9F3",
    benefitsSearch: "#9CC2E5",
    submitForm: "#FCAE70",
    menuOpen: "#CCDBEB",
    search: "#2F528F",
    error: "red",
    input: "#BEC5F0",
    addDrive: "#2F528F",
    black: "#000",
    white: "white",
    blueCircle: "#2D6BAA",
    silverText: "#656565",
    silverTextDrive: "#4B4B4B",
    silverHR: "#707070",
    switchBlue: "#11A7E9",
    switchSilver: "#C8C8C8",
    popupBackground: "#DBE6F1",
    importantNotification: "#FF3838",
    sendMsg: "#00AAF5",
    placeholderTextColor: "black",

}